CREATE TABLE lessons (
    lesson_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    lesson_name VARCHAR2(100),
    PRIMARY KEY (lesson_id)
);

CREATE TABLE tests (
    test_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    lesson_id NUMBER,
    test_name VARCHAR2(100),
    PRIMARY KEY (test_id),
    FOREIGN KEY (lesson_id) REFERENCES lessons(lesson_id)
);

CREATE TABLE questions (
    question_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    test_id NUMBER,
    question_text VARCHAR2(1000),
    choice1 VARCHAR2(100),
    choice2 VARCHAR2(100),
    choice3 VARCHAR2(100),
    choice4 VARCHAR2(100),
    correct_choice NUMBER,
    state NUMBER DEFAULT 0,
    PRIMARY KEY (question_id),
    FOREIGN KEY (test_id) REFERENCES tests(test_id)
);